repos:
  - repo: https://github.com/psf/black
    rev: 21.12b0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
        args: ["--config", "./pyproject.toml"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.931" # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        args: ["--allow-untyped-globals", "--ignore-missing-imports"]
        additional_dependencies: [types-all]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1 # Use the sha / tag you want to point at
    hooks:
      - id: prettier
        types: [javascript]
  - repo: https://github.com/pycqa/flake8
    rev: "4.0.1" # pick a git hash / tag to point to
    hooks:
      - id: flake8
        args:
          [
            "--ignore=E251,E266,E401,E126,E124,C901,E203,E266,E501,W503,W504,F403,F401",
          ]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: "v1.2.0"
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
